# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('timescale')


class _ExportableConfig(types.ModuleType):
    @property
    def access_key(self) -> Optional[str]:
        """
        Access Key
        """
        return __config__.get('accessKey')

    @property
    def access_token(self) -> Optional[str]:
        """
        Access Token
        """
        return __config__.get('accessToken')

    @property
    def project_id(self) -> Optional[str]:
        """
        Project ID
        """
        return __config__.get('projectId')

    @property
    def secret_key(self) -> Optional[str]:
        """
        Secret Key
        """
        return __config__.get('secretKey')

