// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Timescale
{
    public static class GetProducts
    {
        public static Task<GetProductsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetProductsResult>("timescale:index/getProducts:getProducts", InvokeArgs.Empty, options.WithDefaults());

        public static Output<GetProductsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetProductsResult>("timescale:index/getProducts:getProducts", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetProductsResult
    {
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetProductsProductResult> Products;

        [OutputConstructor]
        private GetProductsResult(
            string id,

            ImmutableArray<Outputs.GetProductsProductResult> products)
        {
            Id = id;
            Products = products;
        }
    }
}
