// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Timescale
{
    public static class GetVpcs
    {
        public static Task<GetVpcsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetVpcsResult>("timescale:index/getVpcs:getVpcs", InvokeArgs.Empty, options.WithDefaults());

        public static Output<GetVpcsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetVpcsResult>("timescale:index/getVpcs:getVpcs", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetVpcsResult
    {
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetVpcsVpcResult> Vpcs;

        [OutputConstructor]
        private GetVpcsResult(
            string id,

            ImmutableArray<Outputs.GetVpcsVpcResult> vpcs)
        {
            Id = id;
            Vpcs = vpcs;
        }
    }
}
