// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Timescale.Outputs
{

    [OutputType]
    public sealed class GetServiceResourceSpecResult
    {
        /// <summary>
        /// EnableHAReplica defines if a replica will be provisioned for this service.
        /// </summary>
        public readonly bool EnableHaReplica;
        /// <summary>
        /// MemoryGB is the memory allocated for this service.
        /// </summary>
        public readonly int MemoryGb;
        /// <summary>
        /// MilliCPU is the cpu allocated for this service.
        /// </summary>
        public readonly int MilliCpu;

        [OutputConstructor]
        private GetServiceResourceSpecResult(
            bool enableHaReplica,

            int memoryGb,

            int milliCpu)
        {
            EnableHaReplica = enableHaReplica;
            MemoryGb = memoryGb;
            MilliCpu = milliCpu;
        }
    }
}
