// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Timescale.Outputs
{

    [OutputType]
    public sealed class GetVpcsVpcResult
    {
        public readonly string Cidr;
        public readonly string Created;
        public readonly string ErrorMessage;
        public readonly int Id;
        public readonly string Name;
        public readonly ImmutableArray<Outputs.GetVpcsVpcPeeringConnectionResult> PeeringConnections;
        public readonly string ProjectId;
        public readonly string ProvisionedId;
        public readonly string RegionCode;
        public readonly string Status;
        public readonly string Updated;

        [OutputConstructor]
        private GetVpcsVpcResult(
            string cidr,

            string created,

            string errorMessage,

            int id,

            string name,

            ImmutableArray<Outputs.GetVpcsVpcPeeringConnectionResult> peeringConnections,

            string projectId,

            string provisionedId,

            string regionCode,

            string status,

            string updated)
        {
            Cidr = cidr;
            Created = created;
            ErrorMessage = errorMessage;
            Id = id;
            Name = name;
            PeeringConnections = peeringConnections;
            ProjectId = projectId;
            ProvisionedId = provisionedId;
            RegionCode = regionCode;
            Status = status;
            Updated = updated;
        }
    }
}
