// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Timescale.Outputs
{

    [OutputType]
    public sealed class GetVpcsVpcPeeringConnectionResult
    {
        public readonly string ErrorMessage;
        public readonly string PeerAccountId;
        public readonly string PeerCidr;
        public readonly string PeerRegionCode;
        public readonly string PeerVpcId;
        public readonly string ProvisionedId;
        public readonly string Status;
        public readonly string VpcId;

        [OutputConstructor]
        private GetVpcsVpcPeeringConnectionResult(
            string errorMessage,

            string peerAccountId,

            string peerCidr,

            string peerRegionCode,

            string peerVpcId,

            string provisionedId,

            string status,

            string vpcId)
        {
            ErrorMessage = errorMessage;
            PeerAccountId = peerAccountId;
            PeerCidr = peerCidr;
            PeerRegionCode = peerRegionCode;
            PeerVpcId = peerVpcId;
            ProvisionedId = provisionedId;
            Status = status;
            VpcId = vpcId;
        }
    }
}
