// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package timescale

import (
	"context"
	"reflect"

	"github.com/itoam/pulumi-timescale/sdk/go/timescale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetProducts(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetProductsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetProductsResult
	err := ctx.Invoke("timescale:index/getProducts:getProducts", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getProducts.
type GetProductsResult struct {
	// The ID of this resource.
	Id       string               `pulumi:"id"`
	Products []GetProductsProduct `pulumi:"products"`
}

func GetProductsOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetProductsResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetProductsResultOutput, error) {
		opts = internal.PkgInvokeDefaultOpts(opts)
		var rv GetProductsResult
		secret, err := ctx.InvokePackageRaw("timescale:index/getProducts:getProducts", nil, &rv, "", opts...)
		if err != nil {
			return GetProductsResultOutput{}, err
		}

		output := pulumi.ToOutput(rv).(GetProductsResultOutput)
		if secret {
			return pulumi.ToSecret(output).(GetProductsResultOutput), nil
		}
		return output, nil
	}).(GetProductsResultOutput)
}

// A collection of values returned by getProducts.
type GetProductsResultOutput struct{ *pulumi.OutputState }

func (GetProductsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProductsResult)(nil)).Elem()
}

func (o GetProductsResultOutput) ToGetProductsResultOutput() GetProductsResultOutput {
	return o
}

func (o GetProductsResultOutput) ToGetProductsResultOutputWithContext(ctx context.Context) GetProductsResultOutput {
	return o
}

// The ID of this resource.
func (o GetProductsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetProductsResultOutput) Products() GetProductsProductArrayOutput {
	return o.ApplyT(func(v GetProductsResult) []GetProductsProduct { return v.Products }).(GetProductsProductArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetProductsResultOutput{})
}
