// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package timescale

import (
	"context"
	"reflect"

	"errors"
	"github.com/itoam/pulumi-timescale/sdk/go/timescale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Schema for a peering connection. Import can be done with timescale_vpc_id,peer_account_id,peer_region_code,peer_vpc_id format
type PeeringConnection struct {
	pulumi.CustomResourceState

	ErrorMessage pulumi.StringOutput `pulumi:"errorMessage"`
	// AWS account ID where the VPC to be paired
	PeerAccountId pulumi.StringOutput `pulumi:"peerAccountId"`
	// CIDR for the VPC to be paired
	PeerCidr pulumi.StringOutput `pulumi:"peerCidr"`
	// Region code for the VPC to be paired
	PeerRegionCode pulumi.StringOutput `pulumi:"peerRegionCode"`
	// AWS ID for the VPC to be paired
	PeerVpcId pulumi.StringOutput `pulumi:"peerVpcId"`
	// AWS ID of the peering connection (starts with pcx-...)
	ProvisionedId pulumi.StringOutput `pulumi:"provisionedId"`
	// Peering connection status
	Status pulumi.StringOutput `pulumi:"status"`
	// Timescale internal ID for a vpc
	TimescaleVpcId pulumi.IntOutput `pulumi:"timescaleVpcId"`
	// AWS VPC ID of the timescale instance VPC
	VpcId pulumi.StringOutput `pulumi:"vpcId"`
}

// NewPeeringConnection registers a new resource with the given unique name, arguments, and options.
func NewPeeringConnection(ctx *pulumi.Context,
	name string, args *PeeringConnectionArgs, opts ...pulumi.ResourceOption) (*PeeringConnection, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PeerAccountId == nil {
		return nil, errors.New("invalid value for required argument 'PeerAccountId'")
	}
	if args.PeerRegionCode == nil {
		return nil, errors.New("invalid value for required argument 'PeerRegionCode'")
	}
	if args.PeerVpcId == nil {
		return nil, errors.New("invalid value for required argument 'PeerVpcId'")
	}
	if args.TimescaleVpcId == nil {
		return nil, errors.New("invalid value for required argument 'TimescaleVpcId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PeeringConnection
	err := ctx.RegisterResource("timescale:index/peeringConnection:PeeringConnection", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPeeringConnection gets an existing PeeringConnection resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPeeringConnection(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PeeringConnectionState, opts ...pulumi.ResourceOption) (*PeeringConnection, error) {
	var resource PeeringConnection
	err := ctx.ReadResource("timescale:index/peeringConnection:PeeringConnection", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PeeringConnection resources.
type peeringConnectionState struct {
	ErrorMessage *string `pulumi:"errorMessage"`
	// AWS account ID where the VPC to be paired
	PeerAccountId *string `pulumi:"peerAccountId"`
	// CIDR for the VPC to be paired
	PeerCidr *string `pulumi:"peerCidr"`
	// Region code for the VPC to be paired
	PeerRegionCode *string `pulumi:"peerRegionCode"`
	// AWS ID for the VPC to be paired
	PeerVpcId *string `pulumi:"peerVpcId"`
	// AWS ID of the peering connection (starts with pcx-...)
	ProvisionedId *string `pulumi:"provisionedId"`
	// Peering connection status
	Status *string `pulumi:"status"`
	// Timescale internal ID for a vpc
	TimescaleVpcId *int `pulumi:"timescaleVpcId"`
	// AWS VPC ID of the timescale instance VPC
	VpcId *string `pulumi:"vpcId"`
}

type PeeringConnectionState struct {
	ErrorMessage pulumi.StringPtrInput
	// AWS account ID where the VPC to be paired
	PeerAccountId pulumi.StringPtrInput
	// CIDR for the VPC to be paired
	PeerCidr pulumi.StringPtrInput
	// Region code for the VPC to be paired
	PeerRegionCode pulumi.StringPtrInput
	// AWS ID for the VPC to be paired
	PeerVpcId pulumi.StringPtrInput
	// AWS ID of the peering connection (starts with pcx-...)
	ProvisionedId pulumi.StringPtrInput
	// Peering connection status
	Status pulumi.StringPtrInput
	// Timescale internal ID for a vpc
	TimescaleVpcId pulumi.IntPtrInput
	// AWS VPC ID of the timescale instance VPC
	VpcId pulumi.StringPtrInput
}

func (PeeringConnectionState) ElementType() reflect.Type {
	return reflect.TypeOf((*peeringConnectionState)(nil)).Elem()
}

type peeringConnectionArgs struct {
	// AWS account ID where the VPC to be paired
	PeerAccountId string `pulumi:"peerAccountId"`
	// Region code for the VPC to be paired
	PeerRegionCode string `pulumi:"peerRegionCode"`
	// AWS ID for the VPC to be paired
	PeerVpcId string `pulumi:"peerVpcId"`
	// Timescale internal ID for a vpc
	TimescaleVpcId int `pulumi:"timescaleVpcId"`
}

// The set of arguments for constructing a PeeringConnection resource.
type PeeringConnectionArgs struct {
	// AWS account ID where the VPC to be paired
	PeerAccountId pulumi.StringInput
	// Region code for the VPC to be paired
	PeerRegionCode pulumi.StringInput
	// AWS ID for the VPC to be paired
	PeerVpcId pulumi.StringInput
	// Timescale internal ID for a vpc
	TimescaleVpcId pulumi.IntInput
}

func (PeeringConnectionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*peeringConnectionArgs)(nil)).Elem()
}

type PeeringConnectionInput interface {
	pulumi.Input

	ToPeeringConnectionOutput() PeeringConnectionOutput
	ToPeeringConnectionOutputWithContext(ctx context.Context) PeeringConnectionOutput
}

func (*PeeringConnection) ElementType() reflect.Type {
	return reflect.TypeOf((**PeeringConnection)(nil)).Elem()
}

func (i *PeeringConnection) ToPeeringConnectionOutput() PeeringConnectionOutput {
	return i.ToPeeringConnectionOutputWithContext(context.Background())
}

func (i *PeeringConnection) ToPeeringConnectionOutputWithContext(ctx context.Context) PeeringConnectionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PeeringConnectionOutput)
}

// PeeringConnectionArrayInput is an input type that accepts PeeringConnectionArray and PeeringConnectionArrayOutput values.
// You can construct a concrete instance of `PeeringConnectionArrayInput` via:
//
//	PeeringConnectionArray{ PeeringConnectionArgs{...} }
type PeeringConnectionArrayInput interface {
	pulumi.Input

	ToPeeringConnectionArrayOutput() PeeringConnectionArrayOutput
	ToPeeringConnectionArrayOutputWithContext(context.Context) PeeringConnectionArrayOutput
}

type PeeringConnectionArray []PeeringConnectionInput

func (PeeringConnectionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PeeringConnection)(nil)).Elem()
}

func (i PeeringConnectionArray) ToPeeringConnectionArrayOutput() PeeringConnectionArrayOutput {
	return i.ToPeeringConnectionArrayOutputWithContext(context.Background())
}

func (i PeeringConnectionArray) ToPeeringConnectionArrayOutputWithContext(ctx context.Context) PeeringConnectionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PeeringConnectionArrayOutput)
}

// PeeringConnectionMapInput is an input type that accepts PeeringConnectionMap and PeeringConnectionMapOutput values.
// You can construct a concrete instance of `PeeringConnectionMapInput` via:
//
//	PeeringConnectionMap{ "key": PeeringConnectionArgs{...} }
type PeeringConnectionMapInput interface {
	pulumi.Input

	ToPeeringConnectionMapOutput() PeeringConnectionMapOutput
	ToPeeringConnectionMapOutputWithContext(context.Context) PeeringConnectionMapOutput
}

type PeeringConnectionMap map[string]PeeringConnectionInput

func (PeeringConnectionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PeeringConnection)(nil)).Elem()
}

func (i PeeringConnectionMap) ToPeeringConnectionMapOutput() PeeringConnectionMapOutput {
	return i.ToPeeringConnectionMapOutputWithContext(context.Background())
}

func (i PeeringConnectionMap) ToPeeringConnectionMapOutputWithContext(ctx context.Context) PeeringConnectionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PeeringConnectionMapOutput)
}

type PeeringConnectionOutput struct{ *pulumi.OutputState }

func (PeeringConnectionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PeeringConnection)(nil)).Elem()
}

func (o PeeringConnectionOutput) ToPeeringConnectionOutput() PeeringConnectionOutput {
	return o
}

func (o PeeringConnectionOutput) ToPeeringConnectionOutputWithContext(ctx context.Context) PeeringConnectionOutput {
	return o
}

func (o PeeringConnectionOutput) ErrorMessage() pulumi.StringOutput {
	return o.ApplyT(func(v *PeeringConnection) pulumi.StringOutput { return v.ErrorMessage }).(pulumi.StringOutput)
}

// AWS account ID where the VPC to be paired
func (o PeeringConnectionOutput) PeerAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *PeeringConnection) pulumi.StringOutput { return v.PeerAccountId }).(pulumi.StringOutput)
}

// CIDR for the VPC to be paired
func (o PeeringConnectionOutput) PeerCidr() pulumi.StringOutput {
	return o.ApplyT(func(v *PeeringConnection) pulumi.StringOutput { return v.PeerCidr }).(pulumi.StringOutput)
}

// Region code for the VPC to be paired
func (o PeeringConnectionOutput) PeerRegionCode() pulumi.StringOutput {
	return o.ApplyT(func(v *PeeringConnection) pulumi.StringOutput { return v.PeerRegionCode }).(pulumi.StringOutput)
}

// AWS ID for the VPC to be paired
func (o PeeringConnectionOutput) PeerVpcId() pulumi.StringOutput {
	return o.ApplyT(func(v *PeeringConnection) pulumi.StringOutput { return v.PeerVpcId }).(pulumi.StringOutput)
}

// AWS ID of the peering connection (starts with pcx-...)
func (o PeeringConnectionOutput) ProvisionedId() pulumi.StringOutput {
	return o.ApplyT(func(v *PeeringConnection) pulumi.StringOutput { return v.ProvisionedId }).(pulumi.StringOutput)
}

// Peering connection status
func (o PeeringConnectionOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *PeeringConnection) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Timescale internal ID for a vpc
func (o PeeringConnectionOutput) TimescaleVpcId() pulumi.IntOutput {
	return o.ApplyT(func(v *PeeringConnection) pulumi.IntOutput { return v.TimescaleVpcId }).(pulumi.IntOutput)
}

// AWS VPC ID of the timescale instance VPC
func (o PeeringConnectionOutput) VpcId() pulumi.StringOutput {
	return o.ApplyT(func(v *PeeringConnection) pulumi.StringOutput { return v.VpcId }).(pulumi.StringOutput)
}

type PeeringConnectionArrayOutput struct{ *pulumi.OutputState }

func (PeeringConnectionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PeeringConnection)(nil)).Elem()
}

func (o PeeringConnectionArrayOutput) ToPeeringConnectionArrayOutput() PeeringConnectionArrayOutput {
	return o
}

func (o PeeringConnectionArrayOutput) ToPeeringConnectionArrayOutputWithContext(ctx context.Context) PeeringConnectionArrayOutput {
	return o
}

func (o PeeringConnectionArrayOutput) Index(i pulumi.IntInput) PeeringConnectionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *PeeringConnection {
		return vs[0].([]*PeeringConnection)[vs[1].(int)]
	}).(PeeringConnectionOutput)
}

type PeeringConnectionMapOutput struct{ *pulumi.OutputState }

func (PeeringConnectionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PeeringConnection)(nil)).Elem()
}

func (o PeeringConnectionMapOutput) ToPeeringConnectionMapOutput() PeeringConnectionMapOutput {
	return o
}

func (o PeeringConnectionMapOutput) ToPeeringConnectionMapOutputWithContext(ctx context.Context) PeeringConnectionMapOutput {
	return o
}

func (o PeeringConnectionMapOutput) MapIndex(k pulumi.StringInput) PeeringConnectionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *PeeringConnection {
		return vs[0].(map[string]*PeeringConnection)[vs[1].(string)]
	}).(PeeringConnectionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PeeringConnectionInput)(nil)).Elem(), &PeeringConnection{})
	pulumi.RegisterInputType(reflect.TypeOf((*PeeringConnectionArrayInput)(nil)).Elem(), PeeringConnectionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PeeringConnectionMapInput)(nil)).Elem(), PeeringConnectionMap{})
	pulumi.RegisterOutputType(PeeringConnectionOutput{})
	pulumi.RegisterOutputType(PeeringConnectionArrayOutput{})
	pulumi.RegisterOutputType(PeeringConnectionMapOutput{})
}
