# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .get_products import *
from .get_service import *
from .get_vpcs import *
from .peering_connection import *
from .provider import *
from .service import *
from .vpcs import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_timescale.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_timescale.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "timescale",
  "mod": "index/peeringConnection",
  "fqn": "pulumi_timescale",
  "classes": {
   "timescale:index/peeringConnection:PeeringConnection": "PeeringConnection"
  }
 },
 {
  "pkg": "timescale",
  "mod": "index/service",
  "fqn": "pulumi_timescale",
  "classes": {
   "timescale:index/service:Service": "Service"
  }
 },
 {
  "pkg": "timescale",
  "mod": "index/vpcs",
  "fqn": "pulumi_timescale",
  "classes": {
   "timescale:index/vpcs:Vpcs": "Vpcs"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "timescale",
  "token": "pulumi:providers:timescale",
  "fqn": "pulumi_timescale",
  "class": "Provider"
 }
]
"""
)
