# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ServiceArgs', 'Service']

@pulumi.input_type
class ServiceArgs:
    def __init__(__self__, *,
                 connection_pooler_enabled: Optional[pulumi.Input[bool]] = None,
                 enable_ha_replica: Optional[pulumi.Input[bool]] = None,
                 environment_tag: Optional[pulumi.Input[str]] = None,
                 memory_gb: Optional[pulumi.Input[int]] = None,
                 milli_cpu: Optional[pulumi.Input[int]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 password: Optional[pulumi.Input[str]] = None,
                 paused: Optional[pulumi.Input[bool]] = None,
                 read_replica_source: Optional[pulumi.Input[str]] = None,
                 region_code: Optional[pulumi.Input[str]] = None,
                 storage_gb: Optional[pulumi.Input[int]] = None,
                 timeouts: Optional[pulumi.Input['ServiceTimeoutsArgs']] = None,
                 vpc_id: Optional[pulumi.Input[int]] = None):
        """
        The set of arguments for constructing a Service resource.
        :param pulumi.Input[bool] connection_pooler_enabled: Set connection pooler status for this service.
        :param pulumi.Input[bool] enable_ha_replica: Enable HA Replica
        :param pulumi.Input[str] environment_tag: Set environment tag for this service.
        :param pulumi.Input[int] memory_gb: Memory GB
        :param pulumi.Input[int] milli_cpu: Milli CPU
        :param pulumi.Input[str] name: Service Name is the configurable name assigned to this resource. If none is provided, a default will be generated by the provider.
        :param pulumi.Input[str] password: The Postgres password for this service
        :param pulumi.Input[bool] paused: Paused status of the service.
        :param pulumi.Input[str] read_replica_source: If set, this database will be a read replica of the provided source database. The region must be the same as the source, or if omitted will be handled by the provider
        :param pulumi.Input[str] region_code: The region for this service.
        :param pulumi.Input[int] storage_gb: Deprecated: Storage GB
        :param pulumi.Input[int] vpc_id: The VpcID this service is tied to.
        """
        if connection_pooler_enabled is not None:
            pulumi.set(__self__, "connection_pooler_enabled", connection_pooler_enabled)
        if enable_ha_replica is not None:
            pulumi.set(__self__, "enable_ha_replica", enable_ha_replica)
        if environment_tag is not None:
            pulumi.set(__self__, "environment_tag", environment_tag)
        if memory_gb is not None:
            pulumi.set(__self__, "memory_gb", memory_gb)
        if milli_cpu is not None:
            pulumi.set(__self__, "milli_cpu", milli_cpu)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if paused is not None:
            pulumi.set(__self__, "paused", paused)
        if read_replica_source is not None:
            pulumi.set(__self__, "read_replica_source", read_replica_source)
        if region_code is not None:
            pulumi.set(__self__, "region_code", region_code)
        if storage_gb is not None:
            warnings.warn("""This field is ignored. With the new usage-based storage Timescale automatically allocates the disk space needed by your service and you only pay for the disk space you use.""", DeprecationWarning)
            pulumi.log.warn("""storage_gb is deprecated: This field is ignored. With the new usage-based storage Timescale automatically allocates the disk space needed by your service and you only pay for the disk space you use.""")
        if storage_gb is not None:
            pulumi.set(__self__, "storage_gb", storage_gb)
        if timeouts is not None:
            pulumi.set(__self__, "timeouts", timeouts)
        if vpc_id is not None:
            pulumi.set(__self__, "vpc_id", vpc_id)

    @property
    @pulumi.getter(name="connectionPoolerEnabled")
    def connection_pooler_enabled(self) -> Optional[pulumi.Input[bool]]:
        """
        Set connection pooler status for this service.
        """
        return pulumi.get(self, "connection_pooler_enabled")

    @connection_pooler_enabled.setter
    def connection_pooler_enabled(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "connection_pooler_enabled", value)

    @property
    @pulumi.getter(name="enableHaReplica")
    def enable_ha_replica(self) -> Optional[pulumi.Input[bool]]:
        """
        Enable HA Replica
        """
        return pulumi.get(self, "enable_ha_replica")

    @enable_ha_replica.setter
    def enable_ha_replica(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "enable_ha_replica", value)

    @property
    @pulumi.getter(name="environmentTag")
    def environment_tag(self) -> Optional[pulumi.Input[str]]:
        """
        Set environment tag for this service.
        """
        return pulumi.get(self, "environment_tag")

    @environment_tag.setter
    def environment_tag(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "environment_tag", value)

    @property
    @pulumi.getter(name="memoryGb")
    def memory_gb(self) -> Optional[pulumi.Input[int]]:
        """
        Memory GB
        """
        return pulumi.get(self, "memory_gb")

    @memory_gb.setter
    def memory_gb(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "memory_gb", value)

    @property
    @pulumi.getter(name="milliCpu")
    def milli_cpu(self) -> Optional[pulumi.Input[int]]:
        """
        Milli CPU
        """
        return pulumi.get(self, "milli_cpu")

    @milli_cpu.setter
    def milli_cpu(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "milli_cpu", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        Service Name is the configurable name assigned to this resource. If none is provided, a default will be generated by the provider.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def password(self) -> Optional[pulumi.Input[str]]:
        """
        The Postgres password for this service
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "password", value)

    @property
    @pulumi.getter
    def paused(self) -> Optional[pulumi.Input[bool]]:
        """
        Paused status of the service.
        """
        return pulumi.get(self, "paused")

    @paused.setter
    def paused(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "paused", value)

    @property
    @pulumi.getter(name="readReplicaSource")
    def read_replica_source(self) -> Optional[pulumi.Input[str]]:
        """
        If set, this database will be a read replica of the provided source database. The region must be the same as the source, or if omitted will be handled by the provider
        """
        return pulumi.get(self, "read_replica_source")

    @read_replica_source.setter
    def read_replica_source(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "read_replica_source", value)

    @property
    @pulumi.getter(name="regionCode")
    def region_code(self) -> Optional[pulumi.Input[str]]:
        """
        The region for this service.
        """
        return pulumi.get(self, "region_code")

    @region_code.setter
    def region_code(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "region_code", value)

    @property
    @pulumi.getter(name="storageGb")
    @_utilities.deprecated("""This field is ignored. With the new usage-based storage Timescale automatically allocates the disk space needed by your service and you only pay for the disk space you use.""")
    def storage_gb(self) -> Optional[pulumi.Input[int]]:
        """
        Deprecated: Storage GB
        """
        return pulumi.get(self, "storage_gb")

    @storage_gb.setter
    def storage_gb(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "storage_gb", value)

    @property
    @pulumi.getter
    def timeouts(self) -> Optional[pulumi.Input['ServiceTimeoutsArgs']]:
        return pulumi.get(self, "timeouts")

    @timeouts.setter
    def timeouts(self, value: Optional[pulumi.Input['ServiceTimeoutsArgs']]):
        pulumi.set(self, "timeouts", value)

    @property
    @pulumi.getter(name="vpcId")
    def vpc_id(self) -> Optional[pulumi.Input[int]]:
        """
        The VpcID this service is tied to.
        """
        return pulumi.get(self, "vpc_id")

    @vpc_id.setter
    def vpc_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "vpc_id", value)


@pulumi.input_type
class _ServiceState:
    def __init__(__self__, *,
                 connection_pooler_enabled: Optional[pulumi.Input[bool]] = None,
                 enable_ha_replica: Optional[pulumi.Input[bool]] = None,
                 environment_tag: Optional[pulumi.Input[str]] = None,
                 hostname: Optional[pulumi.Input[str]] = None,
                 memory_gb: Optional[pulumi.Input[int]] = None,
                 milli_cpu: Optional[pulumi.Input[int]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 password: Optional[pulumi.Input[str]] = None,
                 paused: Optional[pulumi.Input[bool]] = None,
                 pooler_hostname: Optional[pulumi.Input[str]] = None,
                 pooler_port: Optional[pulumi.Input[int]] = None,
                 port: Optional[pulumi.Input[int]] = None,
                 read_replica_source: Optional[pulumi.Input[str]] = None,
                 region_code: Optional[pulumi.Input[str]] = None,
                 replica_hostname: Optional[pulumi.Input[str]] = None,
                 replica_port: Optional[pulumi.Input[int]] = None,
                 storage_gb: Optional[pulumi.Input[int]] = None,
                 timeouts: Optional[pulumi.Input['ServiceTimeoutsArgs']] = None,
                 username: Optional[pulumi.Input[str]] = None,
                 vpc_id: Optional[pulumi.Input[int]] = None):
        """
        Input properties used for looking up and filtering Service resources.
        :param pulumi.Input[bool] connection_pooler_enabled: Set connection pooler status for this service.
        :param pulumi.Input[bool] enable_ha_replica: Enable HA Replica
        :param pulumi.Input[str] environment_tag: Set environment tag for this service.
        :param pulumi.Input[str] hostname: The hostname for this service
        :param pulumi.Input[int] memory_gb: Memory GB
        :param pulumi.Input[int] milli_cpu: Milli CPU
        :param pulumi.Input[str] name: Service Name is the configurable name assigned to this resource. If none is provided, a default will be generated by the provider.
        :param pulumi.Input[str] password: The Postgres password for this service
        :param pulumi.Input[bool] paused: Paused status of the service.
        :param pulumi.Input[str] pooler_hostname: Hostname of the pooler of this service.
        :param pulumi.Input[int] pooler_port: Port of the pooler of this service.
        :param pulumi.Input[int] port: The port for this service
        :param pulumi.Input[str] read_replica_source: If set, this database will be a read replica of the provided source database. The region must be the same as the source, or if omitted will be handled by the provider
        :param pulumi.Input[str] region_code: The region for this service.
        :param pulumi.Input[str] replica_hostname: Hostname of the HA-Replica of this service.
        :param pulumi.Input[int] replica_port: Port of the HA-Replica of this service.
        :param pulumi.Input[int] storage_gb: Deprecated: Storage GB
        :param pulumi.Input[str] username: The Postgres user for this service
        :param pulumi.Input[int] vpc_id: The VpcID this service is tied to.
        """
        if connection_pooler_enabled is not None:
            pulumi.set(__self__, "connection_pooler_enabled", connection_pooler_enabled)
        if enable_ha_replica is not None:
            pulumi.set(__self__, "enable_ha_replica", enable_ha_replica)
        if environment_tag is not None:
            pulumi.set(__self__, "environment_tag", environment_tag)
        if hostname is not None:
            pulumi.set(__self__, "hostname", hostname)
        if memory_gb is not None:
            pulumi.set(__self__, "memory_gb", memory_gb)
        if milli_cpu is not None:
            pulumi.set(__self__, "milli_cpu", milli_cpu)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if paused is not None:
            pulumi.set(__self__, "paused", paused)
        if pooler_hostname is not None:
            pulumi.set(__self__, "pooler_hostname", pooler_hostname)
        if pooler_port is not None:
            pulumi.set(__self__, "pooler_port", pooler_port)
        if port is not None:
            pulumi.set(__self__, "port", port)
        if read_replica_source is not None:
            pulumi.set(__self__, "read_replica_source", read_replica_source)
        if region_code is not None:
            pulumi.set(__self__, "region_code", region_code)
        if replica_hostname is not None:
            pulumi.set(__self__, "replica_hostname", replica_hostname)
        if replica_port is not None:
            pulumi.set(__self__, "replica_port", replica_port)
        if storage_gb is not None:
            warnings.warn("""This field is ignored. With the new usage-based storage Timescale automatically allocates the disk space needed by your service and you only pay for the disk space you use.""", DeprecationWarning)
            pulumi.log.warn("""storage_gb is deprecated: This field is ignored. With the new usage-based storage Timescale automatically allocates the disk space needed by your service and you only pay for the disk space you use.""")
        if storage_gb is not None:
            pulumi.set(__self__, "storage_gb", storage_gb)
        if timeouts is not None:
            pulumi.set(__self__, "timeouts", timeouts)
        if username is not None:
            pulumi.set(__self__, "username", username)
        if vpc_id is not None:
            pulumi.set(__self__, "vpc_id", vpc_id)

    @property
    @pulumi.getter(name="connectionPoolerEnabled")
    def connection_pooler_enabled(self) -> Optional[pulumi.Input[bool]]:
        """
        Set connection pooler status for this service.
        """
        return pulumi.get(self, "connection_pooler_enabled")

    @connection_pooler_enabled.setter
    def connection_pooler_enabled(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "connection_pooler_enabled", value)

    @property
    @pulumi.getter(name="enableHaReplica")
    def enable_ha_replica(self) -> Optional[pulumi.Input[bool]]:
        """
        Enable HA Replica
        """
        return pulumi.get(self, "enable_ha_replica")

    @enable_ha_replica.setter
    def enable_ha_replica(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "enable_ha_replica", value)

    @property
    @pulumi.getter(name="environmentTag")
    def environment_tag(self) -> Optional[pulumi.Input[str]]:
        """
        Set environment tag for this service.
        """
        return pulumi.get(self, "environment_tag")

    @environment_tag.setter
    def environment_tag(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "environment_tag", value)

    @property
    @pulumi.getter
    def hostname(self) -> Optional[pulumi.Input[str]]:
        """
        The hostname for this service
        """
        return pulumi.get(self, "hostname")

    @hostname.setter
    def hostname(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "hostname", value)

    @property
    @pulumi.getter(name="memoryGb")
    def memory_gb(self) -> Optional[pulumi.Input[int]]:
        """
        Memory GB
        """
        return pulumi.get(self, "memory_gb")

    @memory_gb.setter
    def memory_gb(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "memory_gb", value)

    @property
    @pulumi.getter(name="milliCpu")
    def milli_cpu(self) -> Optional[pulumi.Input[int]]:
        """
        Milli CPU
        """
        return pulumi.get(self, "milli_cpu")

    @milli_cpu.setter
    def milli_cpu(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "milli_cpu", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        Service Name is the configurable name assigned to this resource. If none is provided, a default will be generated by the provider.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def password(self) -> Optional[pulumi.Input[str]]:
        """
        The Postgres password for this service
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "password", value)

    @property
    @pulumi.getter
    def paused(self) -> Optional[pulumi.Input[bool]]:
        """
        Paused status of the service.
        """
        return pulumi.get(self, "paused")

    @paused.setter
    def paused(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "paused", value)

    @property
    @pulumi.getter(name="poolerHostname")
    def pooler_hostname(self) -> Optional[pulumi.Input[str]]:
        """
        Hostname of the pooler of this service.
        """
        return pulumi.get(self, "pooler_hostname")

    @pooler_hostname.setter
    def pooler_hostname(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "pooler_hostname", value)

    @property
    @pulumi.getter(name="poolerPort")
    def pooler_port(self) -> Optional[pulumi.Input[int]]:
        """
        Port of the pooler of this service.
        """
        return pulumi.get(self, "pooler_port")

    @pooler_port.setter
    def pooler_port(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "pooler_port", value)

    @property
    @pulumi.getter
    def port(self) -> Optional[pulumi.Input[int]]:
        """
        The port for this service
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "port", value)

    @property
    @pulumi.getter(name="readReplicaSource")
    def read_replica_source(self) -> Optional[pulumi.Input[str]]:
        """
        If set, this database will be a read replica of the provided source database. The region must be the same as the source, or if omitted will be handled by the provider
        """
        return pulumi.get(self, "read_replica_source")

    @read_replica_source.setter
    def read_replica_source(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "read_replica_source", value)

    @property
    @pulumi.getter(name="regionCode")
    def region_code(self) -> Optional[pulumi.Input[str]]:
        """
        The region for this service.
        """
        return pulumi.get(self, "region_code")

    @region_code.setter
    def region_code(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "region_code", value)

    @property
    @pulumi.getter(name="replicaHostname")
    def replica_hostname(self) -> Optional[pulumi.Input[str]]:
        """
        Hostname of the HA-Replica of this service.
        """
        return pulumi.get(self, "replica_hostname")

    @replica_hostname.setter
    def replica_hostname(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "replica_hostname", value)

    @property
    @pulumi.getter(name="replicaPort")
    def replica_port(self) -> Optional[pulumi.Input[int]]:
        """
        Port of the HA-Replica of this service.
        """
        return pulumi.get(self, "replica_port")

    @replica_port.setter
    def replica_port(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "replica_port", value)

    @property
    @pulumi.getter(name="storageGb")
    @_utilities.deprecated("""This field is ignored. With the new usage-based storage Timescale automatically allocates the disk space needed by your service and you only pay for the disk space you use.""")
    def storage_gb(self) -> Optional[pulumi.Input[int]]:
        """
        Deprecated: Storage GB
        """
        return pulumi.get(self, "storage_gb")

    @storage_gb.setter
    def storage_gb(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "storage_gb", value)

    @property
    @pulumi.getter
    def timeouts(self) -> Optional[pulumi.Input['ServiceTimeoutsArgs']]:
        return pulumi.get(self, "timeouts")

    @timeouts.setter
    def timeouts(self, value: Optional[pulumi.Input['ServiceTimeoutsArgs']]):
        pulumi.set(self, "timeouts", value)

    @property
    @pulumi.getter
    def username(self) -> Optional[pulumi.Input[str]]:
        """
        The Postgres user for this service
        """
        return pulumi.get(self, "username")

    @username.setter
    def username(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "username", value)

    @property
    @pulumi.getter(name="vpcId")
    def vpc_id(self) -> Optional[pulumi.Input[int]]:
        """
        The VpcID this service is tied to.
        """
        return pulumi.get(self, "vpc_id")

    @vpc_id.setter
    def vpc_id(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "vpc_id", value)


class Service(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 connection_pooler_enabled: Optional[pulumi.Input[bool]] = None,
                 enable_ha_replica: Optional[pulumi.Input[bool]] = None,
                 environment_tag: Optional[pulumi.Input[str]] = None,
                 memory_gb: Optional[pulumi.Input[int]] = None,
                 milli_cpu: Optional[pulumi.Input[int]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 password: Optional[pulumi.Input[str]] = None,
                 paused: Optional[pulumi.Input[bool]] = None,
                 read_replica_source: Optional[pulumi.Input[str]] = None,
                 region_code: Optional[pulumi.Input[str]] = None,
                 storage_gb: Optional[pulumi.Input[int]] = None,
                 timeouts: Optional[pulumi.Input[Union['ServiceTimeoutsArgs', 'ServiceTimeoutsArgsDict']]] = None,
                 vpc_id: Optional[pulumi.Input[int]] = None,
                 __props__=None):
        """
        ## Example Usage

        ```python
        import pulumi
        import pulumi_timescale as timescale

        test = timescale.Service("test")
        # Read replica
        read_replica = timescale.Service("read_replica", read_replica_source=test.id)
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] connection_pooler_enabled: Set connection pooler status for this service.
        :param pulumi.Input[bool] enable_ha_replica: Enable HA Replica
        :param pulumi.Input[str] environment_tag: Set environment tag for this service.
        :param pulumi.Input[int] memory_gb: Memory GB
        :param pulumi.Input[int] milli_cpu: Milli CPU
        :param pulumi.Input[str] name: Service Name is the configurable name assigned to this resource. If none is provided, a default will be generated by the provider.
        :param pulumi.Input[str] password: The Postgres password for this service
        :param pulumi.Input[bool] paused: Paused status of the service.
        :param pulumi.Input[str] read_replica_source: If set, this database will be a read replica of the provided source database. The region must be the same as the source, or if omitted will be handled by the provider
        :param pulumi.Input[str] region_code: The region for this service.
        :param pulumi.Input[int] storage_gb: Deprecated: Storage GB
        :param pulumi.Input[int] vpc_id: The VpcID this service is tied to.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ServiceArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ## Example Usage

        ```python
        import pulumi
        import pulumi_timescale as timescale

        test = timescale.Service("test")
        # Read replica
        read_replica = timescale.Service("read_replica", read_replica_source=test.id)
        ```

        :param str resource_name: The name of the resource.
        :param ServiceArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ServiceArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 connection_pooler_enabled: Optional[pulumi.Input[bool]] = None,
                 enable_ha_replica: Optional[pulumi.Input[bool]] = None,
                 environment_tag: Optional[pulumi.Input[str]] = None,
                 memory_gb: Optional[pulumi.Input[int]] = None,
                 milli_cpu: Optional[pulumi.Input[int]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 password: Optional[pulumi.Input[str]] = None,
                 paused: Optional[pulumi.Input[bool]] = None,
                 read_replica_source: Optional[pulumi.Input[str]] = None,
                 region_code: Optional[pulumi.Input[str]] = None,
                 storage_gb: Optional[pulumi.Input[int]] = None,
                 timeouts: Optional[pulumi.Input[Union['ServiceTimeoutsArgs', 'ServiceTimeoutsArgsDict']]] = None,
                 vpc_id: Optional[pulumi.Input[int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ServiceArgs.__new__(ServiceArgs)

            __props__.__dict__["connection_pooler_enabled"] = connection_pooler_enabled
            __props__.__dict__["enable_ha_replica"] = enable_ha_replica
            __props__.__dict__["environment_tag"] = environment_tag
            __props__.__dict__["memory_gb"] = memory_gb
            __props__.__dict__["milli_cpu"] = milli_cpu
            __props__.__dict__["name"] = name
            __props__.__dict__["password"] = None if password is None else pulumi.Output.secret(password)
            __props__.__dict__["paused"] = paused
            __props__.__dict__["read_replica_source"] = read_replica_source
            __props__.__dict__["region_code"] = region_code
            __props__.__dict__["storage_gb"] = storage_gb
            __props__.__dict__["timeouts"] = timeouts
            __props__.__dict__["vpc_id"] = vpc_id
            __props__.__dict__["hostname"] = None
            __props__.__dict__["pooler_hostname"] = None
            __props__.__dict__["pooler_port"] = None
            __props__.__dict__["port"] = None
            __props__.__dict__["replica_hostname"] = None
            __props__.__dict__["replica_port"] = None
            __props__.__dict__["username"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["password"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Service, __self__).__init__(
            'timescale:index/service:Service',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            connection_pooler_enabled: Optional[pulumi.Input[bool]] = None,
            enable_ha_replica: Optional[pulumi.Input[bool]] = None,
            environment_tag: Optional[pulumi.Input[str]] = None,
            hostname: Optional[pulumi.Input[str]] = None,
            memory_gb: Optional[pulumi.Input[int]] = None,
            milli_cpu: Optional[pulumi.Input[int]] = None,
            name: Optional[pulumi.Input[str]] = None,
            password: Optional[pulumi.Input[str]] = None,
            paused: Optional[pulumi.Input[bool]] = None,
            pooler_hostname: Optional[pulumi.Input[str]] = None,
            pooler_port: Optional[pulumi.Input[int]] = None,
            port: Optional[pulumi.Input[int]] = None,
            read_replica_source: Optional[pulumi.Input[str]] = None,
            region_code: Optional[pulumi.Input[str]] = None,
            replica_hostname: Optional[pulumi.Input[str]] = None,
            replica_port: Optional[pulumi.Input[int]] = None,
            storage_gb: Optional[pulumi.Input[int]] = None,
            timeouts: Optional[pulumi.Input[Union['ServiceTimeoutsArgs', 'ServiceTimeoutsArgsDict']]] = None,
            username: Optional[pulumi.Input[str]] = None,
            vpc_id: Optional[pulumi.Input[int]] = None) -> 'Service':
        """
        Get an existing Service resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] connection_pooler_enabled: Set connection pooler status for this service.
        :param pulumi.Input[bool] enable_ha_replica: Enable HA Replica
        :param pulumi.Input[str] environment_tag: Set environment tag for this service.
        :param pulumi.Input[str] hostname: The hostname for this service
        :param pulumi.Input[int] memory_gb: Memory GB
        :param pulumi.Input[int] milli_cpu: Milli CPU
        :param pulumi.Input[str] name: Service Name is the configurable name assigned to this resource. If none is provided, a default will be generated by the provider.
        :param pulumi.Input[str] password: The Postgres password for this service
        :param pulumi.Input[bool] paused: Paused status of the service.
        :param pulumi.Input[str] pooler_hostname: Hostname of the pooler of this service.
        :param pulumi.Input[int] pooler_port: Port of the pooler of this service.
        :param pulumi.Input[int] port: The port for this service
        :param pulumi.Input[str] read_replica_source: If set, this database will be a read replica of the provided source database. The region must be the same as the source, or if omitted will be handled by the provider
        :param pulumi.Input[str] region_code: The region for this service.
        :param pulumi.Input[str] replica_hostname: Hostname of the HA-Replica of this service.
        :param pulumi.Input[int] replica_port: Port of the HA-Replica of this service.
        :param pulumi.Input[int] storage_gb: Deprecated: Storage GB
        :param pulumi.Input[str] username: The Postgres user for this service
        :param pulumi.Input[int] vpc_id: The VpcID this service is tied to.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ServiceState.__new__(_ServiceState)

        __props__.__dict__["connection_pooler_enabled"] = connection_pooler_enabled
        __props__.__dict__["enable_ha_replica"] = enable_ha_replica
        __props__.__dict__["environment_tag"] = environment_tag
        __props__.__dict__["hostname"] = hostname
        __props__.__dict__["memory_gb"] = memory_gb
        __props__.__dict__["milli_cpu"] = milli_cpu
        __props__.__dict__["name"] = name
        __props__.__dict__["password"] = password
        __props__.__dict__["paused"] = paused
        __props__.__dict__["pooler_hostname"] = pooler_hostname
        __props__.__dict__["pooler_port"] = pooler_port
        __props__.__dict__["port"] = port
        __props__.__dict__["read_replica_source"] = read_replica_source
        __props__.__dict__["region_code"] = region_code
        __props__.__dict__["replica_hostname"] = replica_hostname
        __props__.__dict__["replica_port"] = replica_port
        __props__.__dict__["storage_gb"] = storage_gb
        __props__.__dict__["timeouts"] = timeouts
        __props__.__dict__["username"] = username
        __props__.__dict__["vpc_id"] = vpc_id
        return Service(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="connectionPoolerEnabled")
    def connection_pooler_enabled(self) -> pulumi.Output[bool]:
        """
        Set connection pooler status for this service.
        """
        return pulumi.get(self, "connection_pooler_enabled")

    @property
    @pulumi.getter(name="enableHaReplica")
    def enable_ha_replica(self) -> pulumi.Output[bool]:
        """
        Enable HA Replica
        """
        return pulumi.get(self, "enable_ha_replica")

    @property
    @pulumi.getter(name="environmentTag")
    def environment_tag(self) -> pulumi.Output[str]:
        """
        Set environment tag for this service.
        """
        return pulumi.get(self, "environment_tag")

    @property
    @pulumi.getter
    def hostname(self) -> pulumi.Output[str]:
        """
        The hostname for this service
        """
        return pulumi.get(self, "hostname")

    @property
    @pulumi.getter(name="memoryGb")
    def memory_gb(self) -> pulumi.Output[int]:
        """
        Memory GB
        """
        return pulumi.get(self, "memory_gb")

    @property
    @pulumi.getter(name="milliCpu")
    def milli_cpu(self) -> pulumi.Output[int]:
        """
        Milli CPU
        """
        return pulumi.get(self, "milli_cpu")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        Service Name is the configurable name assigned to this resource. If none is provided, a default will be generated by the provider.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def password(self) -> pulumi.Output[str]:
        """
        The Postgres password for this service
        """
        return pulumi.get(self, "password")

    @property
    @pulumi.getter
    def paused(self) -> pulumi.Output[bool]:
        """
        Paused status of the service.
        """
        return pulumi.get(self, "paused")

    @property
    @pulumi.getter(name="poolerHostname")
    def pooler_hostname(self) -> pulumi.Output[str]:
        """
        Hostname of the pooler of this service.
        """
        return pulumi.get(self, "pooler_hostname")

    @property
    @pulumi.getter(name="poolerPort")
    def pooler_port(self) -> pulumi.Output[int]:
        """
        Port of the pooler of this service.
        """
        return pulumi.get(self, "pooler_port")

    @property
    @pulumi.getter
    def port(self) -> pulumi.Output[int]:
        """
        The port for this service
        """
        return pulumi.get(self, "port")

    @property
    @pulumi.getter(name="readReplicaSource")
    def read_replica_source(self) -> pulumi.Output[Optional[str]]:
        """
        If set, this database will be a read replica of the provided source database. The region must be the same as the source, or if omitted will be handled by the provider
        """
        return pulumi.get(self, "read_replica_source")

    @property
    @pulumi.getter(name="regionCode")
    def region_code(self) -> pulumi.Output[str]:
        """
        The region for this service.
        """
        return pulumi.get(self, "region_code")

    @property
    @pulumi.getter(name="replicaHostname")
    def replica_hostname(self) -> pulumi.Output[str]:
        """
        Hostname of the HA-Replica of this service.
        """
        return pulumi.get(self, "replica_hostname")

    @property
    @pulumi.getter(name="replicaPort")
    def replica_port(self) -> pulumi.Output[int]:
        """
        Port of the HA-Replica of this service.
        """
        return pulumi.get(self, "replica_port")

    @property
    @pulumi.getter(name="storageGb")
    @_utilities.deprecated("""This field is ignored. With the new usage-based storage Timescale automatically allocates the disk space needed by your service and you only pay for the disk space you use.""")
    def storage_gb(self) -> pulumi.Output[Optional[int]]:
        """
        Deprecated: Storage GB
        """
        return pulumi.get(self, "storage_gb")

    @property
    @pulumi.getter
    def timeouts(self) -> pulumi.Output[Optional['outputs.ServiceTimeouts']]:
        return pulumi.get(self, "timeouts")

    @property
    @pulumi.getter
    def username(self) -> pulumi.Output[str]:
        """
        The Postgres user for this service
        """
        return pulumi.get(self, "username")

    @property
    @pulumi.getter(name="vpcId")
    def vpc_id(self) -> pulumi.Output[Optional[int]]:
        """
        The VpcID this service is tied to.
        """
        return pulumi.get(self, "vpc_id")

