// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getProducts(opts?: pulumi.InvokeOptions): Promise<GetProductsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("timescale:index/getProducts:getProducts", {
    }, opts);
}

/**
 * A collection of values returned by getProducts.
 */
export interface GetProductsResult {
    /**
     * The ID of this resource.
     */
    readonly id: string;
    readonly products: outputs.GetProductsProduct[];
}
export function getProductsOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetProductsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("timescale:index/getProducts:getProducts", {
    }, opts);
}
